In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Python

**Task 1** (0.5 points)<br/> 
Enter numbers `a`,  `d` и `N`. Find sum of the first `N` members of arithmetic progression with the first member `a` and difference `d`, without using formula for the sum.

In [2]:
def sum_arithmetic_progression(a, d, N):
    s = 0
    
    for i in range(N):
        s += (a + i * d)
        
    return s

In [3]:
def sum_arithmetic_progression(a, d, N):
    x, s = a, 0

    for _ in range(N):
        s += x
        x = x + d
        
    return s

In [4]:
sum_arithmetic_progression(1, 2, 3)

9

In [5]:
sum_arithmetic_progression(2, 4, 5)

50

In [6]:
sum_arithmetic_progression(3, 3, 0)

0

In [7]:
sum_arithmetic_progression(1, 0, 1000000)

1000000

**Task 2** (0.5 points) <br/> 
Enter a number `N`. Find sum of the first `N` memebers of harmonic series.

In [8]:
def sum_harmonic_series(N):
    s = 0
    
    for i in range(1, N + 1):
        s += 1 / i 
        
    return s

In [9]:
sum_harmonic_series(1)

1.0

In [10]:
sum_harmonic_series(2)

1.5

In [11]:
sum_harmonic_series(8)

2.7178571428571425

In [12]:
sum_harmonic_series(1000000)

14.392726722864989

**Task 3** (0.5 points) <br/> 
Enter an integer number `N`. Check if it is a prime number.

In [13]:
from math import sqrt

def is_prime(N):
    N = abs(N)
    
    if N == 0 or N == 1:
        return False
    
    for i in range(2, int(sqrt(N)) + 1):
        if N % i == 0:
            return False
        i += 1
    
    return True

In [14]:
is_prime(2)

True

In [15]:
is_prime(31)

True

In [16]:
is_prime(26)

False

In [17]:
is_prime(10**9 + 7)

True

**Task 4** (0.5 points) <br/> 
Enter the first `N` prime numbers.

In [18]:
def prime_numbers(N):
    x, i = [], 2
    
    while len(x) != N:
        if is_prime(i): x.append(i)
        i += 1
        
    return x

In [19]:
prime_numbers(5)

[2, 3, 5, 7, 11]

In [20]:
prime_numbers(9)

[2, 3, 5, 7, 11, 13, 17, 19, 23]

In [21]:
prime_numbers(20)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71]

**Task 5** (0.5 points) <br/> 
There are numbers: `a`, `b`, `c`. Without using functions `min`, `max` and other functions, find the maximum number.

In [22]:
def max_number(a, b, c):
    if a < b:
        if b < c:
            return c
        else:
            return b
    else:
        if a < c:
            return c
        else:
            return a

In [23]:
def max_number(a, b, c):
    m = a
    
    if m < b: m = b
        
    if m < c: m = c
            
    return m

In [24]:
max_number(1, 2, 3)

3

In [25]:
max_number(4, 10, -2)

10

In [26]:
max_number(7, 1, 5)

7

In [27]:
max_number(6, 6, 6)

6

# 2. Numpy

**Task 1** (0.5 points) <br/>
Create two random arrays $a$ and $b$ with the same length. 

Calculate the following distances between the arrays:

* Euclidean Distance
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Manhattan Distance
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Cosine Distance
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$


In [28]:
import numpy as np
from math import sqrt

def euclidean_distance(a, b):
    ed = 0
    
    for i in range (0, len(a)):
        ed += (a[i] - b[i]) ** 2
    
    return np.sqrt(ed)

def manhattan_distance(a, b):
    md = 0
    
    for i in range (0, len(a)):
        md += np.abs(a[i] - b[i])
        
    return md

def cosine_distance(a, b):
    return 1 - np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [29]:
a = np.random.randint(0, 10, 3)
b = np.random.randint(0, 10, 3)

In [30]:
euclidean_distance(a , b)

11.789826122551595

In [31]:
manhattan_distance(a, b)

19

In [32]:
cosine_distance(a, b)

0.5407516021703604

In [33]:
import scipy.spatial.distance

In [34]:
scipy.spatial.distance.euclidean(a, b)

11.789826122551595

In [35]:
scipy.spatial.distance.cityblock(a, b)

19

In [36]:
scipy.spatial.distance.cosine(a, b)

0.5407516021703604

**Task 2** (0.5 points) <br/>
Create a random array (`np.random.rand()`) with length of 10 and with sum of its elements equals to 2.

In [37]:
import numpy as np

arr = np.random.rand(10)
arr = arr * (2 / np.sum(arr))

print(arr)
print(np.sum(arr))

[0.18643985 0.17105348 0.19192491 0.02307981 0.2074536  0.25679699
 0.15221986 0.26911781 0.26745803 0.27445566]
2.0


In [38]:
import numpy as np

arr = []

for _ in range(10):
    arr.append(np.random.rand())

arr = np.array(arr)
arr = arr * (2 / np.sum(arr))

print(arr)
print(np.sum(arr))

[0.41145535 0.12956543 0.12133844 0.23520107 0.41935371 0.17517833
 0.02953996 0.02456735 0.01960725 0.4341931 ]
2.0


**Task 3** (0.5 points) <br/>
Create a random array (`np.random.rand()`) with length of 100. Transform the array so, that 
* Maximum element(s) value is 1
* Minimum element(s) value is 0
* Other values are in interval 0-1 with keeping the order

In [39]:
import numpy as np

arr = np.random.rand(100)
arr = (arr - arr.min()) / (arr.max() - arr.min())

print(arr)

[0.50695028 0.96423042 0.44052113 0.29012114 0.11420006 0.7172399
 0.21140038 0.70641638 0.37648514 0.40088001 0.91010205 0.88202807
 0.92063154 0.41289288 0.74225341 0.68100166 0.60967384 0.66295096
 0.7210651  0.7973757  0.75950559 0.00135633 0.53663077 0.06172158
 0.41887151 0.0532828  0.40432827 0.34011296 0.67111286 0.35854911
 0.07465865 0.71919182 0.84856449 0.08266728 0.7455089  0.85490817
 0.64283273 0.79117434 0.54982734 1.         0.80328023 0.5805873
 0.62513415 0.53989941 0.8766785  0.06034102 0.65236462 0.51036457
 0.29785238 0.50186991 0.28205998 0.79653542 0.45951073 0.11484616
 0.10106519 0.96146554 0.40653339 0.70977741 0.7937284  0.25782377
 0.42972746 0.82917276 0.15558116 0.61668931 0.5028007  0.69810436
 0.08677599 0.21324241 0.9655618  0.00376369 0.95957869 0.78133427
 0.50795358 0.05383989 0.65600933 0.86120165 0.48700615 0.64532015
 0.73795373 0.18905696 0.21745192 0.95366127 0.81189727 0.
 0.27825356 0.82043582 0.10357482 0.3789009  0.73963949 0.42616629
 0.16

In [40]:
import numpy as np

arr = []

for _ in range(100):
    arr.append(np.random.rand())

arr = np.array(arr)
arr = (arr - arr.min()) / (arr.max() - arr.min())

print(arr)

[0.50598153 0.63808768 0.46366725 0.66576861 0.53735554 0.01403093
 0.51126502 0.76906605 0.97224757 0.77192515 0.24292087 0.37006266
 0.46264091 0.10630299 0.37988377 0.19977685 0.19138045 0.08600129
 0.68380976 0.00954895 0.45821998 0.42081707 0.07316627 0.26097905
 0.63187041 0.12415092 0.81272681 0.64933083 0.7235386  0.08007671
 0.49490401 0.77838328 0.45307723 0.23493975 0.64998013 0.01747495
 0.47916031 0.99470076 0.47496329 0.87393288 0.83954304 0.95978918
 0.95568707 0.70501672 0.72311576 0.18924168 0.33220538 0.95633074
 0.87480155 0.63807709 0.69089306 0.76675904 0.60734405 0.75368435
 0.23439361 0.72315593 1.         0.63458723 0.06437914 0.01693813
 0.60169463 0.48662388 0.55346866 0.54737213 0.65636558 0.21478319
 0.81708034 0.76528377 0.1836008  0.20410535 0.8940587  0.00377607
 0.93152027 0.64603925 0.01346263 0.62994416 0.29822676 0.94658357
 0.46130517 0.12698739 0.25422949 0.53373842 0.31081632 0.
 0.20904242 0.17421867 0.66255821 0.01282257 0.72288421 0.42358304
 0.

**Task 4** (0.5 points) <br/>
Create a random array with length of 20 with integers from [0,50]. Select elements that are smaller than 5th percentile and larger than 95th percentile

In [41]:
import numpy as np

arr = np.random.randint(0, 50, 20)

print(arr)

smaller = []
larger = []

ps = np.percentile(arr, 5)
print(ps)
pl = np.percentile(arr, 95)
print(pl)

for i in range(20):
    if arr[i] < ps:
        smaller.append(arr[i])
    if arr[i] > pl:
        larger.append(arr[i])
        
print(smaller)
print(larger)

[30 46 38 30  4 28 27 29 12 17 42 42 24 39 15  9 17 12 10 35]
8.75
42.2
[4]
[46]


**Task 5** (0.5 points) <br/>
Create an array with shape of $5 \times 6$ with integer from [0,50]. Print a column that contains the maximum element of the array.

In [42]:
import numpy as np

arr = np.random.randint(0, 50, (5, 6))
print(arr)

m, cs = arr.max(), arr.argmax()

print(m, cs)

column = cs % 6

print(column)

print(np.array([arr[:, column]]).T)

[[20 24 47  8 15 31]
 [31  1 23 44 36 32]
 [41 32 39  0 21 24]
 [ 7  3 45 11 15 13]
 [36 42 33  3 20 29]]
47 2
2
[[47]
 [23]
 [39]
 [45]
 [33]]


**Task 6** (0.5 points) <br/>

Replace all missing values in the following array with mean.

In [43]:
arr = np.random.rand(10)
idx = np.random.randint(0, 10, 4)
arr[idx] = np.nan
print(arr)

arr[np.isnan(arr)] = np.nanmean(arr)
        
print(arr)

[0.84413873 0.37533381        nan 0.19355977        nan 0.61444777
        nan 0.84279584 0.38105792        nan]
[0.84413873 0.37533381 0.54188897 0.19355977 0.54188897 0.61444777
 0.54188897 0.84279584 0.38105792 0.54188897]


### Linear Regression

Download [file 1](https://www.dropbox.com/s/kg9px9v3xfysak9/tutorial_dataset.csv?dl=0) and [file 2](https://www.dropbox.com/s/f87gm612o144emx/tutorial_dataset_2.csv?dl=0) into a directory with this notebook. Using function `loadtxt` in `numpy` load data from the first file. Assign y = D[:,0] аnd X = D[:, 1:].


We will use one magic formula to find linear regression coefficients. You will prove this formula on your next lectures of the course.

Linear regression model in matrix form looks like: $\hat{y} = X\hat{\beta}$, where

$$ \hat{\beta} = (X^\top X)^{-1} X^\top y $$
Model residuals are calculated as
$$ \text{res} = y - \hat{y} $$


**Task 7** (2.5 points)<br/>
1. Load the data
2. Find parameters $\hat{\beta}$ using the formula above
3. Make a plot with the model residuals on Y axis and $\hat{y}$ on X axis

In [44]:
D = np.loadtxt('tutorial_dataset.csv', 
               skiprows = 1, 
               delimiter = ',')



OSError: tutorial_dataset.csv not found.

# 3. Pandas

### Wine Quality

Download [sample](https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv) with information about wine characteristics and its quality.

In [ ]:
## Your code here

**Task 1 ** (1 point) <br/>
* How much objects are in the sample?
* What features describe the objects? How much these features?
* What is feature a target variable?
* What are their ranges?
* Are there any missing values?

In [ ]:
## Your code and answers here

**Task 2** (1 point)<br/>
What features affect the target variable the most?

In [ ]:
## Your code here